version: "3.8"

services:
  wago-ai-suite:
    image: wagoalex/wago-ai-suite-ui:latest
    container_name: wago-ai-suite
    ports:
      - "443:443"
    volumes:
      - /docker/tests:/app
      - /etc/docker/certs:/etc/docker/certs
    environment:
      - REACT_APP_MQTT_BROKER_URL=${REACT_APP_MQTT_BROKER_URL}
      - REACT_APP_MQTT_START_TOPIC=${REACT_APP_MQTT_START_TOPIC}
      - REACT_APP_N8N_API_URL=${REACT_APP_N8N_API_URL}
      - REACT_APP_N8N_REST_API_KEY=${REACT_APP_N8N_REST_API_KEY}
      - SERVER_NAME=${SERVER_NAME}
      - INFERENCE_URL=${INFERENCE_URL}
    depends_on:
      - wago-ai-suite-backend
      - wago-label-studio
    networks:
      - waa_cm_network

  wago-ai-suite-backend:
    image: wagoalex/wago-ai-suite-backend:latest
    container_name: wago-ai-suite-backend
    ports:
      - "3042:3042"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/ssl:/app/ssl
      - /docker/tests:/app/audio
      - /etc/docker/certs:/etc/docker/certs
    environment:
      - API_KEY=${API_KEY}
      - INFERENCE_URL=${INFERENCE_URL}
    networks:
      - waa_cm_network

  wago-label-studio:
    image: heartexlabs/label-studio:latest
    container_name: wago-label-studio
    ports:
      - "8080:8080"
    volumes:
      - /docker/labelstudio/data:/label-studio/data
    environment:
      - LABEL_STUDIO_USERNAME=admin
      - LABEL_STUDIO_PASSWORD=wagowago
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=false
      - LABEL_STUDIO_DISABLE_CSP=true
      - LABEL_STUDIO_HOST=https://192.168.2.165
      - LABEL_STUDIO_BASE_URL=/labelstudio
      - STATIC_URL=/labelstudio/static/
      - DEBUG=false
      - ALLOWED_HOSTS=*
      - FORCE_SCRIPT_NAME=/labelstudio
      - DJANGO_USE_X_FORWARDED_HOST=true
      - DJANGO_USE_X_FORWARDED_PORT=true
      - DJANGO_SESSION_COOKIE_SECURE=false
      - DJANGO_CSRF_COOKIE_SECURE=false
      - DJANGO_SESSION_COOKIE_PATH=/labelstudio/
      - DJANGO_CSRF_COOKIE_PATH=/labelstudio/
      - DJANGO_SESSION_COOKIE_SAMESITE=Lax
      - DJANGO_CSRF_COOKIE_SAMESITE=Lax
      - LABEL_STUDIO_PUBLIC_URL=https://192.168.2.165/labelstudio
      - COLLECT_ANALYTICS=False

    networks:
      - waa_cm_network

volumes:
  wago-label-studio-data:

networks:
  waa_cm_network:
    external: true
